/**
 * Nederlandse Spoorwegen station names and their corresponding station codes
 */
export const STATIONS: Record<string, string> = {
  "Aalten": "Atn",
  "Abcoude": "Ac",
  "Akkrum": "Akm",
  "Alkmaar": "Amr",
  "Alkmaar Noord": "Amrn",
  "Almelo": "Aml",
  "Almelo De Riet": "Amri",
  "Almere Buiten": "Almb",
  "Almere Centrum": "Alm",
  "Almere Muziekwijk": "Almm",
  "Almere Oostvaarders": "Almo",
  "Almere Parkwijk": "Almp",
  "Almere Poort": "Ampo",
  "Alphen a/d Rijn": "Apn",
  "Amersfoort Centraal": "Amf",
  "Amersfoort Schothorst": "Amfs",
  "Amersfoort Vathorst": "Avat",
  "Amsterdam Amstel": "Asa",
  "Amsterdam ArenA": "Asdar",
  "Amsterdam Bijlmer ArenA": "Asb",
  "Amsterdam Centraal": "Asd",
  "Amsterdam Holendrecht": "Ashd",
  "Amsterdam Lelylaan": "Asdl",
  "Amsterdam Muiderpoort": "Asdm",
  "Amsterdam RAI": "Rai",
  "Amsterdam Science Park": "Assp",
  "Amsterdam Sloterdijk": "Ass",
  "Amsterdam Zuid": "Asdz",
  "Anna Paulowna": "Ana",
  "Apeldoorn": "Apd",
  "Apeldoorn De Maten": "Apdm",
  "Apeldoorn Osseveld": "Apdo",
  "Appingedam": "Apg",
  "Arkel": "Akl",
  "Arnemuiden": "Arn",
  "Arnhem Centraal": "Ah",
  "Arnhem Presikhaaf": "Ahpr",
  "Arnhem Velperpoort": "Ahp",
  "Arnhem Zuid": "Ahz",
  "Assen": "Asn",
  "Baarn": "Brn",
  "Bad Nieuweschans": "Nsch",
  "Baflo": "Bf",
  "Barendrecht": "Brd",
  "Barneveld Centrum": "Bnc",
  "Barneveld Noord": "Bnn",
  "Barneveld Zuid": "Bnz",
  "Bedum": "Bdm",
  "Beek-Elsloo": "Bk",
  "Beesd": "Bsd",
  "Beilen": "Bl",
  "Bergen op Zoom": "Bgn",
  "Best": "Bet",
  "Beverwijk": "Bv",
  "Bilthoven": "Bhv",
  "Blerick": "Br",
  "Bloemendaal": "Bll",
  "Bodegraven": "Bdg",
  "Borne": "Bn",
  "Boskoop": "Bsk",
  "Boskoop Snijdelwijk": "Bsks",
  "Boven Hardinxveld": "Bhdv",
  "Bovenkarspel Flora": "Bkf",
  "Bovenkarspel-Grootebroek": "Bkg",
  "Boxmeer": "Bmr",
  "Boxtel": "Btl",
  "Breda": "Bd",
  "Breda-Prinsenbeek": "Bdpb",
  "Breukelen": "Bkl",
  "Brummen": "Bmn",
  "Buitenpost": "Bp",
  "Bunde": "Bde",
  "Bunnik": "Bnk",
  "Bussum Zuid": "Bsmz",
  "Capelle Schollevaar": "Cps",
  "Castricum": "Cas",
  "Chevremont": "Cvm",
  "Coevorden": "Co",
  "Cuijk": "Ck",
  "Culemborg": "Cl",
  "Daarlerveen": "Da",
  "Dalen": "Dln",
  "Dalfsen": "Dl",
  "De Vink": "Dvnk",
  "De Westereen": "Dwe",
  "Deinum": "Dei",
  "Delden": "Ddn",
  "Delft": "Dt",
  "Delft Campus": "Dtcp",
  "Delfzijl": "Dz",
  "Delfzijl West": "Dzw",
  "Den Dolder": "Dld",
  "Den Haag Centraal": "Gvc",
  "Den Haag HS": "Gv",
  "Den Haag Laan van NOI": "Laa",
  "Den Haag Mariahoeve": "Gvm",
  "Den Haag Moerwijk": "Gvmw",
  "Den Haag Ypenburg": "Ypb",
  "Den Helder": "Hdr",
  "Den Helder Zuid": "Hdrz",
  "Deurne": "Dn",
  "Deventer": "Dv",
  "Deventer Colmschate": "Dvc",
  "Didam": "Did",
  "Diemen": "Dmn",
  "Diemen Zuid": "Dmnz",
  "Dieren": "Dr",
  "Doetinchem": "Dtc",
  "Doetinchem De Huet": "Dtch",
  "Dordrecht": "Ddr",
  "Dordrecht Stadspolders": "Ddrs",
  "Dordrecht Zuid": "Ddzd",
  "Driebergen-Zeist": "Db",
  "Driehuis": "Drh",
  "Dronryp": "Drp",
  "Dronten": "Dron",
  "Duiven": "Dvn",
  "Duivendrecht": "Dvd",
  "Echt": "Ec",
  "Ede Centrum": "Edc",
  "Ede-Wageningen": "Ed",
  "Eemshaven": "Eem",
  "Eijsden": "Edn",
  "Eindhoven Centraal": "Ehv",
  "Eindhoven Stadion": "Ehst",
  "Eindhoven Strijp-S": "Ehs",
  "Elst": "Est",
  "Emmen": "Emn",
  "Emmen Zuid": "Emnz",
  "Enkhuizen": "Ekz",
  "Enschede": "Es",
  "Enschede De Eschmarke": "Ese",
  "Enschede Kennispark": "Esk",
  "Ermelo": "Eml",
  "Etten-Leur": "Etn",
  "Eygelshoven": "Egh",
  "Eygelshoven Markt": "Eghm",
  "Feanwâlden": "Fwd",
  "Franeker": "Fn",
  "Gaanderen": "Gdr",
  "Geldermalsen": "Gdm",
  "Geldrop": "Gp",
  "Geleen-Lutterade": "Lut",
  "Geleen Oost": "Gln",
  "Gilze-Rijen": "Gz",
  "Glanerbrug": "Gbr",
  "Goes": "Gs",
  "Goor": "Go",
  "Gorinchem": "Gr",
  "Gouda": "Gd",
  "Gouda Goverwelle": "Gdg",
  "Gramsbergen": "Gbg",
  "Grijpskerk": "Gk",
  "Groningen": "Gn",
  "Groningen Europapark": "Gerp",
  "Groningen Noord": "Gnn",
  "Grou-Jirnsum": "Gw",
  "Haarlem": "Hlm",
  "Haarlem Spaarnwoude": "Hlms",
  "Halfweg-Zwanenburg": "Hwzb",
  "'t Harde": "Hde",
  "Hardenberg": "Hdb",
  "Harderwijk": "Hd",
  "Hardinxveld Blauwe Zoom": "Hbzm",
  "Hardinxveld-Giessendam": "Gnd",
  "Haren": "Hrn",
  "Harlingen": "Hlg",
  "Harlingen Haven": "Hlgh",
  "Heemskerk": "Hk",
  "Heemstede-Aerdenhout": "Had",
  "Heerenveen": "Hr",
  "Heerhugowaard": "Hwd",
  "Heerlen": "Hrl",
  "Heerlen Woonboulevard": "Hrlw",
  "Heeze": "Hze",
  "Heiloo": "Hlo",
  "Heino": "Hno",
  "Helmond": "Hm",
  "Helmond Brandevoort": "Hmbv",
  "Helmond Brouwhuis": "Hmbh",
  "Helmond 't Hout": "Hmh",
  "Hemmen-Dodewaard": "Hmn",
  "Hengelo": "Hgl",
  "Hengelo Gezondheidspark": "Hglg",
  "Hengelo Oost": "Hglo",
  "'s-Hertogenbosch": "Ht",
  "'s-Hertogenbosch Oost": "Hto",
  "Hillegom": "Hil",
  "Hilversum": "Hvs",
  "Hilversum Media Park": "Hvsm",
  "Hilversum Sportpark": "Hvsp",
  "Hindeloopen": "Hnp",
  "Hoensbroek": "Hb",
  "Hoevelaken": "Hvl",
  "Hollandsche Rading": "Hor",
  "Holten": "Hon",
  "Hoofddorp": "Hfd",
  "Hoogeveen": "Hgv",
  "Hoogezand-Sappemeer": "Hgz",
  "Hoogkarspel": "Hks",
  "Hoorn": "Hn",
  "Hoorn Kersenboogerd": "Hnk",
  "Horst-Sevenum": "Hrt",
  "Houten": "Htn",
  "Houten Castellum": "Htnc",
  "Houthem-Sint Gerlach": "Sgl",
  "Hurdegaryp": "Hdg",
  "IJlst": "IJt",
  "Kampen": "Kpn",
  "Kampen Zuid": "Kpnz",
  "Kapelle-Biezelinge": "Bzl",
  "Kerkrade Centrum": "Krd",
  "Kesteren": "Ktr",
  "Klarenbeek": "Kbk",
  "Klimmen-Ransdaal": "Kmr",
  "Koog aan de Zaan": "Kz",
  "Koudum-Molkwerum": "Kmw",
  "Krabbendijke": "Kbd",
  "Krommenie-Assendelft": "Kma",
  "Kropswolde": "Kw",
  "Kruiningen-Yerseke": "Krg",
  "Lage Zwaluwe": "Zlw",
  "Landgraaf": "Lg",
  "Lansingerland-Zoetermeer": "Llzm",
  "Leerdam": "Ldm",
  "Leeuwarden": "Lw",
  "Leeuwarden Camminghaburen": "Lwc",
  "Leiden Centraal": "Ledn",
  "Leiden Lammenschans": "Ldl",
  "Lelystad Centrum": "Lls",
  "Lichtenvoorde-Groenlo": "Ltv",
  "Lochem": "Lc",
  "Loppersum": "Lp",
  "Lunteren": "Ltn",
  "Maarheeze": "Mz",
  "Maarn": "Mrn",
  "Maarssen": "Mas",
  "Maastricht": "Mt",
  "Maastricht Noord": "Mtn",
  "Maastricht Randwyck": "Mtr",
  "Mantgum": "Mg",
  "Mariënberg": "Mrb",
  "Martenshoek": "Mth",
  "Meerssen": "Mes",
  "Meppel": "Mp",
  "Middelburg": "Mdb",
  "Mook-Molenhoek": "Mmlh",
  "Naarden-Bussum": "Ndb",
  "Nieuw Amsterdam": "Na",
  "Nieuw Vennep": "Nvp",
  "Nieuwerkerk a/d IJssel": "Nwk",
  "Nijkerk": "Nkk",
  "Nijmegen": "Nm",
  "Nijmegen Dukenburg": "Nmd",
  "Nijmegen Goffert": "Nmgo",
  "Nijmegen Heyendaal": "Nmh",
  "Nijmegen Lent": "Nml",
  "Nijverdal": "Nvd",
  "Nunspeet": "Ns",
  "Nuth": "Nh",
  "Obdam": "Obd",
  "Oisterwijk": "Ot",
  "Oldenzaal": "Odz",
  "Olst": "Ost",
  "Ommen": "Omn",
  "Oosterbeek": "Otb",
  "Opheusden": "Op",
  "Oss": "O",
  "Oss West": "Ow",
  "Oudenbosch": "Odb",
  "Overveen": "Ovn",
  "Purmerend": "Pmr",
  "Purmerend Overwhere": "Pmo",
  "Purmerend Weidevenne": "Pmw",
  "Putten": "Pt",
  "Raalte": "Rat",
  "Ravenstein": "Rvs",
  "Reuver": "Rv",
  "Rheden": "Rh",
  "Rhenen": "Rhn",
  "Rijssen": "Rsn",
  "Rijswijk": "Rsw",
  "Rilland-Bath": "Rb",
  "Roermond": "Rm",
  "Roodeschool": "Rd",
  "Roosendaal": "Rsd",
  "Rosmalen": "Rs",
  "Rotterdam Alexander": "Rta",
  "Rotterdam Blaak": "Rtb",
  "Rotterdam Centraal": "Rtd",
  "Rotterdam Lombardijen": "Rlb",
  "Rotterdam Noord": "Rtn",
  "Rotterdam Stadion": "Rtst",
  "Rotterdam Zuid": "Rtz",
  "Ruurlo": "Rl",
  "Santpoort Noord": "Sptn",
  "Santpoort Zuid": "Sptz",
  "Sassenheim": "Ssh",
  "Sauwerd": "Swd",
  "Schagen": "Sgn",
  "Scheemda": "Sda",
  "Schiedam Centrum": "Sdm",
  "Schin op Geul": "Sog",
  "Schinnen": "Sn",
  "Schiphol Airport": "Shl",
  "Sittard": "Std",
  "Sliedrecht": "Sdt",
  "Sliedrecht Baanhoek": "Sdtb",
  "Sneek": "Sk",
  "Sneek Noord": "Sknd",
  "Soest": "St",
  "Soest Zuid": "Stz",
  "Soestdijk": "Sd",
  "Spaubeek": "Sbk",
  "Stavoren": "Stv",
  "Stedum": "Stm",
  "Steenwijk": "Swk",
  "Susteren": "Srn",
  "Swalmen": "Sm",
  "Tegelen": "Tg",
  "Terborg": "Tbg",
  "Tiel": "Tl",
  "Tiel Passewaaij": "Tpsw",
  "Tilburg": "Tb",
  "Tilburg Reeshof": "Tbr",
  "Tilburg Universiteit": "Tbu",
  "Twello": "Twl",
  "Uitgeest": "Utg",
  "Uithuizen": "Uhz",
  "Uithuizermeeden": "Uhm",
  "Usquert": "Ust",
  "Utrecht Centraal": "Ut",
  "Utrecht Leidsche Rijn": "Utlr",
  "Utrecht Lunetten": "Utln",
  "Utrecht Maliebaan": "Utm",
  "Utrecht Overvecht": "Uto",
  "Utrecht Terwijde": "Utt",
  "Utrecht Vaartsche Rijn": "Utvr",
  "Utrecht Zuilen": "Utzl",
  "Valkenburg": "Vk",
  "Varsseveld": "Vsv",
  "Veendam": "Vdm",
  "Veenendaal Centrum": "Vndc",
  "Veenendaal-De Klomp": "Klp",
  "Veenendaal West": "Vndw",
  "Velp": "Vp",
  "Venlo": "Vl",
  "Venray": "Vry",
  "Vierlingsbeek": "Vlb",
  "Vleuten": "Vtn",
  "Vlissingen": "Vs",
  "Vlissingen Souburg": "Vss",
  "Voerendaal": "Vdl",
  "Voorburg": "Vb",
  "Voorhout": "Vh",
  "Voorschoten": "Vst",
  "Voorst-Empe": "Vem",
  "Vorden": "Vd",
  "Vriezenveen": "Vz",
  "Vroomshoop": "Vhp",
  "Vught": "Vg",
  "Waddinxveen": "Wad",
  "Waddinxveen Noord": "Wadn",
  "Waddinxveen Triangel": "Wadt",
  "Warffum": "Wfm",
  "Weert": "Wt",
  "Weesp": "Wp",
  "Wehl": "Wl",
  "Westervoort": "Wtv",
  "Wezep": "Wz",
  "Wierden": "Wdn",
  "Wijchen": "Wc",
  "Wijhe": "Wh",
  "Winschoten": "Ws",
  "Winsum": "Wsm",
  "Winterswijk": "Ww",
  "Winterswijk West": "Www",
  "Woerden": "Wd",
  "Wolfheze": "Wf",
  "Wolvega": "Wv",
  "Workum": "Wk",
  "Wormerveer": "Wm",
  "Zaandam": "Zd",
  "Zaandam Kogerveld": "Zdk",
  "Zaandijk Zaanse Schans": "Zzs",
  "Zaltbommel": "Zbm",
  "Zandvoort aan Zee": "Zvt",
  "Zetten-Andelst": "Za",
  "Zevenaar": "Zv",
  "Zevenbergen": "Zvb",
  "Zoetermeer": "Ztm",
  "Zoetermeer Oost": "Ztmo",
  "Zuidbroek": "Zb",
  "Zuidhorn": "Zh",
  "Zutphen": "Zp",
  "Zwijndrecht": "Zwd",
  "Zwolle": "Zl",
  "Zwolle Stadshagen": "Zlsh",
};
